name: biolink_dbt
version: 1.0.0
profile: biolink_dbt
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  biolink_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
