"""
BioLink JSON-to-SQL Processor for Apache NiFi 2.8.0

Converts validated unified JSON records into PostgreSQL INSERT/UPSERT
SQL statements for a configured target table.

Updated to support fully dynamic column sets (wide standardized tables
bhs_participants and ehvol_participants generated by SchemaStandardizer).
The column list is derived directly from the incoming record keys;
no hardcoded UNIFIED_COLUMNS list is required.
"""

import json
from collections import OrderedDict
from nifiapi.flowfiletransform import FlowFileTransform, FlowFileTransformResult
from nifiapi.properties import PropertyDescriptor, ExpressionLanguageScope

# Internal keys that should NOT become SQL columns.
# _ingest_id  — BIGSERIAL, generated by PostgreSQL
# _sdtm_standardized — pipeline-internal boolean flag
# _source_row — zero-based row counter added by CsvToJson
# _rejection_reasons — DataQuality audit list (not a table column)
_SKIP_KEYS = frozenset([
    "_ingest_id",
    "_sdtm_standardized",
    "_source_row",
    "_rejection_reasons",
])

# Backward-compatible aliases for records coming from older pipeline stages.
# Generated wide tables use underscore-prefixed metadata column names.
_KEY_ALIASES = {
    "source_dataset": "_source_dataset",
    "ingested_at": "_ingested_at",
    "data_quality_score": "_data_quality_score",
}


def _normalize_record_keys(record):
    normalized = OrderedDict()
    for key, value in record.items():
        canonical = _KEY_ALIASES.get(key, key)
        if canonical in _SKIP_KEYS:
            continue
        normalized[canonical] = value
    return normalized


def _sql_value(val):
    """Convert a Python value to SQL literal."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    # JSON/dict/list -> JSONB literal
    if isinstance(val, (dict, list)):
        s = json.dumps(val).replace("'", "''")
        return f"'{s}'::jsonb"

    # Escape single quotes for strings
    s = str(val).replace("'", "''")
    return f"'{s}'"


class BiolinkJsonToSqlProcessor(FlowFileTransform):
    """
    Converts validated unified JSON records into PostgreSQL
    INSERT … ON CONFLICT UPDATE statements.
    """

    class Java:
        implements = ["org.apache.nifi.python.processor.FlowFileTransform"]

    class ProcessorDetails:
        version = "1.0.0"
        description = (
            "Converts unified BioLink JSON records to PostgreSQL INSERT "
            "statements targeting a configured dataset table. "
            "Supports upsert (ON CONFLICT DO UPDATE)."
        )
        tags = ["biolink", "sql", "postgresql", "etl"]

    TABLE_NAME = PropertyDescriptor(
        name="Table Name",
        description="Target PostgreSQL table name",
        required=True,
        default_value="bhs_participants",
        expression_language_scope=ExpressionLanguageScope.FLOWFILE_ATTRIBUTES,
    )

    UPSERT_MODE = PropertyDescriptor(
        name="Upsert Mode",
        description=(
            "Use ON CONFLICT DO NOTHING (for wide standardized tables) "
            "or ON CONFLICT (participant_id) DO UPDATE for the legacy narrow table. "
            "Set to 'false' for wide tables with a BIGSERIAL PK."
        ),
        required=False,
        default_value="false",
        allowable_values=["true", "false"],
        expression_language_scope=ExpressionLanguageScope.FLOWFILE_ATTRIBUTES,
    )

    CONFLICT_COLUMN = PropertyDescriptor(
        name="Conflict Column",
        description="Column to use in ON CONFLICT clause when Upsert Mode is true. Leave blank to use ON CONFLICT DO NOTHING.",
        required=False,
        default_value="",
        expression_language_scope=ExpressionLanguageScope.FLOWFILE_ATTRIBUTES,
    )

    property_descriptors = [TABLE_NAME, UPSERT_MODE, CONFLICT_COLUMN]

    def __init__(self, **kwargs):
        super().__init__()

    def getPropertyDescriptors(self):
        return self.property_descriptors

    def transform(self, context, flowfile):
        table         = context.getProperty(self.TABLE_NAME).evaluateAttributeExpressions(flowfile).getValue()
        upsert        = context.getProperty(self.UPSERT_MODE).evaluateAttributeExpressions(flowfile).getValue() == "true"
        conflict_col  = (context.getProperty(self.CONFLICT_COLUMN).evaluateAttributeExpressions(flowfile).getValue() or "").strip()

        try:
            raw = json.loads(flowfile.getContentsAsBytes().decode("utf-8"))
        except Exception as e:
            return FlowFileTransformResult(
                relationship="failure",
                contents=json.dumps({"error": f"Invalid JSON: {e}"}),
                attributes={"biolink.error": str(e)},
            )

        records = raw if isinstance(raw, list) else [raw]
        if not records:
            return FlowFileTransformResult(
                relationship="failure",
                contents=json.dumps({"error": "No records found in input JSON"}),
                attributes={"biolink.error": "No records found in input JSON"},
            )

        output = self._build_bulk_sql(records, table, upsert, conflict_col) + ";\n"

        return FlowFileTransformResult(
            relationship="success",
            contents=output,
            attributes={
                "biolink.sql.statement_count": "1",
                "biolink.sql.record_count": str(len(records)),
                "biolink.sql.table": table,
                "mime.type": "text/plain",
            },
        )

    def _build_bulk_sql(self, records, table, upsert, conflict_col=""):
        # Build a union of keys across every record to prevent silent value loss
        # when records within the same batch have non-identical key sets.
        normalized_records = [_normalize_record_keys(record) for record in records]

        ordered_cols = OrderedDict()
        for record in normalized_records:
            for key in record.keys():
                ordered_cols.setdefault(key, None)
        cols = list(ordered_cols.keys())

        if not cols:
            raise ValueError("No SQL columns found after filtering internal keys")

        col_sql = ", ".join(f'"{c}"' for c in cols)

        # Conflict / upsert clause
        if upsert and conflict_col:
            update_pairs = [
                f'"{c}" = EXCLUDED."{c}"'
                for c in cols
                if c != conflict_col
            ]
            conflict_suffix = (
                f' ON CONFLICT ("{conflict_col}") DO UPDATE SET '
                + ", ".join(update_pairs)
            )
        elif upsert:
            conflict_suffix = " ON CONFLICT DO NOTHING"
        else:
            conflict_suffix = ""

        # Build value rows for every record in this FlowFile batch.
        row_values = []
        for record in normalized_records:
            vals = [_sql_value(record.get(c)) for c in cols]
            row_values.append(f"({', '.join(vals)})")

        val_list = ",\n".join(row_values)
        return f'INSERT INTO "{table}" ({col_sql}) VALUES\n{val_list}{conflict_suffix}'
