"""
BioLink Schema Standardizer Processor for Apache NiFi 2.8.0

Applies the CDISC SDTM / LOINC / SNOMED / ICD-10 / UCUM column
standardization to every row of a BHS or EHVol CSV-derived JSON record.

Pipeline position:
  CsvToJson → SchemaStandardizer → DataQuality → JsonToSql → PutSQL

Column maps are Python modules generated alongside this file by
scripts/generate_schema_sql.py and imported at first use:
  nifi/processors/bhs_col_map.py    (COLUMN_MAP dict)
  nifi/processors/ehvol_col_map.py  (COLUMN_MAP dict)

The canonical schema metadata lives in the _schema_registry PostgreSQL table
(also populated by scripts/generate_schema_sql.py via db/schema_standardized.sql).

Properties:
  Dataset Type   - "bhs" or "ehvol"
  Include Raw JSON - attach _source_raw_json field
"""

import importlib.util
import json
import os
import re
from datetime import datetime, timezone

from nifiapi.flowfiletransform import FlowFileTransform, FlowFileTransformResult
from nifiapi.properties import PropertyDescriptor, ExpressionLanguageScope


# ─────────────────────────────────────────────────────────────
# Type coercion helpers
# ─────────────────────────────────────────────────────────────

def _safe_str(v):
    if v is None:
        return None
    s = str(v).strip()
    return s if s else None


def to_bool(v, _ds=None):
    s = _safe_str(v)
    if s is None:
        return None
    sl = s.lower()
    if sl in ("yes", "y", "true", "t", "1", "checked", "check"):
        return True
    if sl in ("no", "n", "false", "f", "0", "unchecked", "uncheck"):
        return False
    return None


def to_float(v, _ds=None):
    s = _safe_str(v)
    if s is None:
        return None
    s = s.replace(",", "").replace(" ", "")
    if "-" in s:
        parts = s.split("-")
        try:
            nums = [float(p) for p in parts if p.strip()]
            if nums:
                return sum(nums) / len(nums)
        except ValueError:
            pass
    try:
        return float(s)
    except ValueError:
        return None


def to_int(v, _ds=None):
    f = to_float(v)
    return int(round(f)) if f is not None else None


_DATE_FORMATS = [
    "%Y-%m-%d", "%Y/%m/%d", "%d/%m/%Y", "%d-%m-%Y",
    "%d.%m.%Y", "%m/%d/%Y", "%m-%d-%Y", "%m.%d.%Y",
    "%d/%m/%y", "%d-%m-%y", "%m/%d/%y", "%m-%d-%y",
]


def to_date(v, _ds=None):
    s = _safe_str(v)
    if s is None:
        return None
    s = re.split(r"[T ]", s, maxsplit=1)[0].strip()
    s = re.sub(r"[.]0+$", "", s)
    for fmt in _DATE_FORMATS:
        try:
            parsed = datetime.strptime(s, fmt)
            if 1900 <= parsed.year <= datetime.utcnow().year + 1:
                return parsed.strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def to_str(v, _ds=None):
    return _safe_str(v)


_COERCE = {
    "to_bool":  to_bool,
    "to_float": to_float,
    "to_int":   to_int,
    "to_date":  to_date,
    "to_str":   to_str,
}

# ─────────────────────────────────────────────────────────────
# Snake-case helper (mirrors generate_schema_sql.py)
# ─────────────────────────────────────────────────────────────
_MAX_PG = 63


def _to_snake(name: str) -> str:
    s = str(name).strip()
    s = re.sub(r"[^a-zA-Z0-9]+", "_", s)
    s = s.strip("_").lower()
    s = re.sub(r"_+", "_", s)
    if not s or s[0].isdigit():
        s = "col_" + s
    return s[:_MAX_PG]


# ─────────────────────────────────────────────────────────────
# Column-map loader — imports the generated *_col_map.py module
# that lives in the same processors/ directory.
# ─────────────────────────────────────────────────────────────
_map_cache: dict = {}   # { "bhs" | "ehvol" : COLUMN_MAP dict }
_HERE = os.path.dirname(os.path.abspath(__file__))


def _get_col_map(dataset: str) -> dict:
    key = dataset.lower()
    if key in _map_cache:
        return _map_cache[key]
    mod_name = f"{key}_col_map"
    mod_path = os.path.join(_HERE, f"{mod_name}.py")
    spec = importlib.util.spec_from_file_location(mod_name, mod_path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    _map_cache[key] = mod.COLUMN_MAP
    return mod.COLUMN_MAP


# ─────────────────────────────────────────────────────────────
# NiFi Processor
# ─────────────────────────────────────────────────────────────
class BiolinkSchemaStandardizerProcessor(FlowFileTransform):
    """
    Applies SDTM/LOINC/UCUM column standardization to raw BioLink JSON records.

    Input:  JSON object with original CSV column names as keys.
    Output: JSON object with snake_case pg_col_name keys and coerced values,
            plus audit metadata (_source_dataset, _ingested_at, _sdtm_standardized).

    Column maps are loaded from co-located *_col_map.py modules (generated by
    scripts/generate_schema_sql.py). The authoritative schema lives in the
    _schema_registry PostgreSQL table.
    """

    class Java:
        implements = ["org.apache.nifi.python.processor.FlowFileTransform"]

    class ProcessorDetails:
        version = "1.0.0"
        description = (
            "Standardizes BioLink dataset columns according to CDISC SDTM, "
            "LOINC, SNOMED CT, ICD-10, and UCUM guidelines. "
            "Renames columns to snake_case PostgreSQL names and coerces types. "
            "Column mapping is loaded from co-located *_col_map.py Python modules."
        )
        tags = ["biolink", "standardize", "sdtm", "loinc", "ucum", "etl"]

    DATASET_TYPE = PropertyDescriptor(
        name="Dataset Type",
        description="Source dataset: bhs or ehvol",
        required=True,
        default_value="bhs",
        allowable_values=["bhs", "ehvol"],
        expression_language_scope=ExpressionLanguageScope.FLOWFILE_ATTRIBUTES,
    )

    INCLUDE_RAW_JSON = PropertyDescriptor(
        name="Include Raw JSON",
        description="Attach the original source record as _source_raw_json field",
        required=False,
        default_value="false",
        allowable_values=["true", "false"],
        expression_language_scope=ExpressionLanguageScope.FLOWFILE_ATTRIBUTES,
    )

    property_descriptors = [DATASET_TYPE, INCLUDE_RAW_JSON]

    def __init__(self, **kwargs):
        super().__init__()

    def getPropertyDescriptors(self):
        return self.property_descriptors

    def transform(self, context, flowfile):
        dataset     = context.getProperty(self.DATASET_TYPE).evaluateAttributeExpressions(flowfile).getValue().lower()
        include_raw = context.getProperty(self.INCLUDE_RAW_JSON).evaluateAttributeExpressions(flowfile).getValue() == "true"

        try:
            raw_bytes = flowfile.getContentsAsBytes()
            source_record = json.loads(raw_bytes.decode("utf-8-sig"))
        except Exception as e:
            return FlowFileTransformResult(
                relationship="failure",
                contents=json.dumps({"error": f"JSON parse error: {e}"}),
                attributes={"biolink.error": str(e), "biolink.stage": "standardize"},
            )

        records = source_record if isinstance(source_record, list) else [source_record]

        try:
            col_map = _get_col_map(dataset)
        except Exception as e:
            return FlowFileTransformResult(
                relationship="failure",
                contents=json.dumps({"error": f"Column map load error: {e}"}),
                attributes={"biolink.error": str(e), "biolink.stage": "col_map_load"},
            )

        now_iso = datetime.now(timezone.utc).isoformat()
        standardized = []
        for rec in records:
            out = {
                "_source_dataset":    dataset.upper(),
                "_ingested_at":       now_iso,
                "_sdtm_standardized": True,
            }
            if include_raw:
                out["_source_raw_json"] = rec
            for orig_col, value in rec.items():
                if orig_col in col_map:
                    pg_col, coerce_fn = col_map[orig_col]
                    out[pg_col] = _COERCE[coerce_fn](value, dataset)
                else:
                    # Unknown column: drop from output to avoid INSERT errors
                    # for columns that don't exist in the target table.
                    # Set Include Raw JSON=true to preserve unmapped source fields.
                    pass
            standardized.append(out)

        output = standardized if isinstance(source_record, list) else standardized[0]
        return FlowFileTransformResult(
            relationship="success",
            contents=json.dumps(output, default=str),
            attributes={
                "biolink.dataset":   dataset.upper(),
                "biolink.stage":     "standardized",
                "biolink.col_count": str(len(col_map)),
            },
        )

