#!/usr/bin/env python3
"""
STEP 2: Apply master_schema.csv to raw CSVs → outputs/unified_registry.csv

Reads master_schema.csv (generated by two_stage_match.py) and applies it
to one or more raw datasets, producing a single PII-free, harmonised registry
with full terminology normalization and per-field provenance tracking.

Scientific properties
---------------------
1. **Variable-level rules** — every harmonized column is governed by an
   explicit VariableRule (unit, allowable range/values, phenotype definition,
   timing window, transform function) imported from variable_rules.py.
2. **Terminology normalization** — raw heterogeneous values are normalized
   through typed transforms (normalize_boolean, normalize_gender, etc.)
   enforced at transform time, not just structural column selection.
3. **Per-field provenance** — each (row, column) cell in the output is tracked
   in a provenance log: source column(s), source value, transform applied,
   harmonized value, validation status, confidence, and reviewer flag.
   Saved to outputs/provenance.csv alongside the main registry.
4. **Harmonization tiers** — every column is tagged as one of:
     schema_aligned           — column names matched; raw values pass through
     semantically_harmonized  — terminology normalized; values validated
     analysis_ready           — unit-standardized, range-validated, phenotype-defined
   Tier assignments come from variable_rules.py and are exported in
   outputs/harmonization_tiers.csv.
5. **Cohort comparability hooks** — the unified registry includes a ``cohort``
   column so downstream scripts (cohort_comparability.py) can run distribution,
   missingness, and protocol-difference analyses before pooling.

Usage
-----
  python scripts/apply_schema.py \\
      outputs/master_schema.csv \\
      db/BHS_Full.csv db/EHVol_Full.csv \\
      --output outputs/unified_registry.csv
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import warnings
from pathlib import Path
from typing import Any, Dict, List, Optional

warnings.filterwarnings("ignore")

try:
    import pandas as pd
    import numpy as np
except ImportError:
    sys.exit("pandas and numpy are required: pip install pandas numpy")

# Import variable rules and transforms (same directory)
sys.path.insert(0, str(Path(__file__).resolve().parent))
from variable_rules import VARIABLE_RULES, VariableRule, get_rule
from harmonize_transforms import (
    TRANSFORM_DISPATCH,
    apply_transform,
    validate_allowable,
    validate_range,
)


# ---------------------------------------------------------------------------
# Column-name normalisation (mirrors two_stage_match.to_snake)
# ---------------------------------------------------------------------------

def to_snake(name: str) -> str:
    """Normalise an arbitrary column heading to snake_case."""
    name = name.lower().strip()
    name = re.sub(r"['\u2019\u2018]", "", name)      # apostrophes
    name = re.sub(r"[^a-z0-9 _]", " ", name)
    name = re.sub(r"\s+", "_", name.strip())
    name = re.sub(r"_+", "_", name)
    return name.strip("_")


def _load_csv(path: Path) -> pd.DataFrame:
    """
    Load a CSV and normalise column names to snake_case, matching the
    convention used by two_stage_match.py when generating master_schema.csv.
    Duplicate snake names get _2, _3 … suffixes.
    """
    df = pd.read_csv(path, dtype=str, low_memory=False)
    snake_cols: List[str] = [to_snake(c) for c in df.columns]
    seen: Dict[str, int] = {}
    final: List[str] = []
    for sc in snake_cols:
        if sc in seen:
            seen[sc] += 1
            final.append(f"{sc}_{seen[sc]}")
        else:
            seen[sc] = 0
            final.append(sc)
    df.columns = final
    return df


# ---------------------------------------------------------------------------
# Coalesce strategies
# ---------------------------------------------------------------------------

def _coalesce(df_temp: pd.DataFrame, strategy: str) -> pd.Series:
    """
    Given a DataFrame where each column is a source column for the same
    master field (rows = patients), coalesce across columns using `strategy`.
    Returns a Series aligned on df_temp.index.
    """
    if df_temp.empty or df_temp.shape[1] == 0:
        return pd.Series(np.nan, index=df_temp.index, dtype=object)

    if strategy == "first_non_null":
        # bfill across columns, take first
        return df_temp.bfill(axis=1).iloc[:, 0]

    elif strategy == "mean_value":
        num = df_temp.apply(pd.to_numeric, errors="coerce")
        return num.mean(axis=1, skipna=True)

    elif strategy == "max_value":
        num = df_temp.apply(pd.to_numeric, errors="coerce")
        return num.max(axis=1, skipna=True)

    elif strategy == "min_value":
        num = df_temp.apply(pd.to_numeric, errors="coerce")
        return num.min(axis=1, skipna=True)

    elif strategy == "any_flag":
        # 1 if at least one truthy non-null value, else 0, NaN if all null
        def _any_row(row: pd.Series) -> Optional[int]:
            valid = row.dropna()
            if valid.empty:
                return np.nan
            try:
                return int(valid.astype(float).astype(bool).any())
            except (ValueError, TypeError):
                return int(valid.str.lower().isin({"1", "yes", "true", "y"}).any())
        return df_temp.apply(_any_row, axis=1)

    elif strategy == "all_flag":
        def _all_row(row: pd.Series) -> Optional[int]:
            valid = row.dropna()
            if valid.empty:
                return np.nan
            try:
                return int(valid.astype(float).astype(bool).all())
            except (ValueError, TypeError):
                return int(valid.str.lower().isin({"1", "yes", "true", "y"}).all())
        return df_temp.apply(_all_row, axis=1)

    elif strategy == "mode_value":
        def _mode_row(row: pd.Series):
            valid = row.dropna()
            if valid.empty:
                return np.nan
            modes = valid.mode()
            return modes.iloc[0]
        return df_temp.apply(_mode_row, axis=1)

    elif strategy == "median_date":
        # Parse each column as datetime, compute median timestamp, return ISO date
        def _parse_col(s: pd.Series) -> pd.Series:
            return pd.to_datetime(s, errors="coerce", infer_datetime_format=True)

        parsed = pd.concat([_parse_col(df_temp[c]) for c in df_temp.columns], axis=1)
        parsed.columns = range(parsed.shape[1])
        # Convert to int (ns epoch), median, back to datetime
        numeric = parsed.apply(lambda s: s.view("int64").where(parsed.notna().any(axis=1), np.nan))
        median_ns = numeric.median(axis=1, skipna=True)
        median_dt = pd.to_datetime(median_ns, unit="ns", errors="coerce")
        return median_dt.dt.date.astype(str).where(median_dt.notna(), np.nan)

    else:
        raise ValueError(
            f"Unknown coalesce strategy: '{strategy}'. "
            "Valid: first_non_null, mean_value, max_value, min_value, "
            "any_flag, all_flag, mode_value, median_date"
        )


# ---------------------------------------------------------------------------
# Dataset processing
# ---------------------------------------------------------------------------

def _resolve_source_cols(
    schema_row: pd.Series,
    df: pd.DataFrame,
) -> List[str]:
    """
    Return the list of columns in `df` that correspond to this schema row.

    Detection order (stops at first non-empty match):
      1. source_a_cols (comma-separated)
      2. source_b_cols (comma-separated)
      3. Any col in df that exactly matches either list
    This makes processing order-independent — no need to label datasets as A/B.
    """
    def _parse(field: str) -> List[str]:
        return [c.strip() for c in str(field).split(",") if c.strip()]

    cols_a = [c for c in _parse(schema_row.get("source_a_cols", "")) if c in df.columns]
    if cols_a:
        return cols_a

    cols_b = [c for c in _parse(schema_row.get("source_b_cols", "")) if c in df.columns]
    if cols_b:
        return cols_b

    return []


def process_dataset(
    df: pd.DataFrame,
    schema: pd.DataFrame,
    cohort_label: str,
) -> tuple[pd.DataFrame, List[Dict[str, Any]]]:
    """
    Apply master schema to one raw DataFrame with full normalization
    and provenance tracking.

    Returns:
        (result_df, provenance_records)
        - result_df: DataFrame with columns `cohort` + one column per non-PII
          master schema entry, with values normalized per variable rules.
        - provenance_records: list of dicts, one per (row, column) cell that
          had a source value, recording the full transformation lineage.
    """
    non_pii_schema = schema[~schema["pii_flag"].astype(bool)].copy()

    result_cols: dict[str, pd.Series] = {"cohort": pd.Series(cohort_label, index=df.index)}
    provenance_records: List[Dict[str, Any]] = []

    covered = 0
    normalized = 0
    validation_failures = 0

    for _, srow in non_pii_schema.iterrows():
        master_col = srow["master_col"]
        strategy   = srow.get("coalesce_strategy", "first_non_null")
        rule       = get_rule(master_col)

        source_cols = _resolve_source_cols(srow, df)
        if not source_cols:
            result_cols[master_col] = pd.Series(np.nan, index=df.index)
            continue

        covered += 1
        src_df = df[source_cols].copy()
        src_df.columns = range(len(source_cols))

        # Step 1: Coalesce raw values (structural merge)
        raw_series = _coalesce(src_df, strategy)

        # Step 2: Apply terminology normalization transform (if rule specifies one)
        transform_name = rule.transform
        has_transform = transform_name is not None and transform_name in TRANSFORM_DISPATCH

        if has_transform:
            harmonized_values = []
            for idx, raw_val in raw_series.items():
                if pd.isna(raw_val):
                    harmonized_values.append(np.nan)
                    continue

                h_val = apply_transform(raw_val, transform_name)

                # Validate
                valid = True
                reason = None
                if h_val is not None:
                    if rule.data_type == "numeric" and rule.allowable_range:
                        valid, reason = validate_range(h_val, rule.allowable_range)
                    elif rule.data_type == "categorical" and rule.allowable_values:
                        valid, reason = validate_allowable(h_val, rule.allowable_values)

                if not valid:
                    validation_failures += 1
                    # Record out-of-range but keep original value with flag
                    provenance_records.append({
                        "row_index": idx,
                        "cohort": cohort_label,
                        "master_col": master_col,
                        "source_cols": ",".join(source_cols),
                        "source_value": str(raw_val),
                        "transform": transform_name or "",
                        "harmonized_value": str(h_val) if h_val is not None else "",
                        "validation_status": "FAIL",
                        "validation_reason": reason or "",
                        "tier": rule.tier,
                        "unit": rule.unit or "",
                        "confidence": "low",
                        "reviewer_approved": False,
                    })
                    harmonized_values.append(np.nan)  # null out invalid values
                else:
                    # Record successful transform provenance
                    if str(raw_val) != str(h_val):
                        provenance_records.append({
                            "row_index": idx,
                            "cohort": cohort_label,
                            "master_col": master_col,
                            "source_cols": ",".join(source_cols),
                            "source_value": str(raw_val),
                            "transform": transform_name or "",
                            "harmonized_value": str(h_val) if h_val is not None else "",
                            "validation_status": "PASS",
                            "validation_reason": "",
                            "tier": rule.tier,
                            "unit": rule.unit or "",
                            "confidence": "high" if rule.tier == "analysis_ready" else "medium",
                            "reviewer_approved": False,
                        })
                    harmonized_values.append(h_val)

            result_cols[master_col] = pd.Series(harmonized_values, index=raw_series.index)
            normalized += 1
        else:
            # No transform — schema_aligned passthrough
            result_cols[master_col] = raw_series

    result = pd.DataFrame(result_cols, index=df.index)

    # Drop rows that are entirely NaN across all clinical columns
    clinical_cols = [c for c in result.columns if c != "cohort"]
    result = result.dropna(subset=clinical_cols, how="all")

    print(
        f"  [{cohort_label}] {len(df):>6} rows in → {len(result):>6} rows out  "
        f"| {covered}/{len(non_pii_schema)} schema cols matched  "
        f"| {normalized} normalized  | {validation_failures} validation failures"
    )
    return result, provenance_records


# ---------------------------------------------------------------------------
# PII audit
# ---------------------------------------------------------------------------

def _pii_audit(schema: pd.DataFrame) -> None:
    pii_rows = schema[schema["pii_flag"].astype(bool)]
    if pii_rows.empty:
        print("\n  [PII] No PII-flagged columns — all schema entries included.")
        return
    print(f"\n  [PII] {len(pii_rows)} column(s) DROPPED (pii_flag=True):")
    for _, r in pii_rows.iterrows():
        print(f"    {r['master_col']:40}  (A: {r['source_a_cols']}  B: {r['source_b_cols']})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="STEP 2: Apply master_schema.csv to raw CSVs → unified_registry.csv",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/apply_schema.py outputs/master_schema.csv \\
      db/BHS_Full.csv db/EHVol_Full.csv

  python scripts/apply_schema.py outputs/master_schema.csv \\
      db/BHS_Full.csv db/EHVol_Full.csv db/NewCohort.csv \\
      --output outputs/unified_registry.csv
        """,
    )
    parser.add_argument("schema",   help="Path to master_schema.csv (from two_stage_match.py)")
    parser.add_argument("datasets", nargs="+", help="Raw CSV files (2 or more)")
    parser.add_argument(
        "--output", "-o",
        default="outputs/unified_registry.csv",
        help="Output path for unified registry (default: outputs/unified_registry.csv)",
    )
    parser.add_argument(
        "--drop-empty-cols",
        action="store_true",
        help="Drop master columns that are entirely NaN across ALL cohorts",
    )
    parser.add_argument(
        "--provenance-output",
        default="outputs/provenance.csv",
        help="Output path for per-field provenance log (default: outputs/provenance.csv)",
    )
    parser.add_argument(
        "--tiers-output",
        default="outputs/harmonization_tiers.csv",
        help="Output path for harmonization tier classification (default: outputs/harmonization_tiers.csv)",
    )
    args = parser.parse_args()

    schema_path = Path(args.schema)
    if not schema_path.exists():
        sys.exit(f"Schema not found: {schema_path}\nRun two_stage_match.py first.")

    print("Loading master schema …")
    schema = pd.read_csv(schema_path)

    # Normalise pii_flag: CSV stores 'True'/'False' strings
    schema["pii_flag"] = schema["pii_flag"].astype(str).str.lower().isin({"true", "1", "yes"})

    n_total = len(schema)
    n_pii   = int(schema["pii_flag"].sum())
    print(f"  {n_total} master columns  |  {n_pii} PII-flagged  |  {n_total - n_pii} clinical")
    _pii_audit(schema)

    # ---- Process each dataset ----
    print(f"\nProcessing {len(args.datasets)} dataset(s) …")
    unified_parts: List[pd.DataFrame] = []
    all_provenance: List[Dict[str, Any]] = []
    for i, ds_path in enumerate(args.datasets):
        p = Path(ds_path)
        if not p.exists():
            print(f"  WARNING: dataset not found, skipping: {p}", file=sys.stderr)
            continue
        label = f"D{i + 1}"
        print(f"\n  Loading {p.name} → cohort '{label}' …")
        try:
            df_raw = _load_csv(p)
        except Exception as e:
            print(f"  ERROR reading {p}: {e}  — skipping.", file=sys.stderr)
            continue
        cohort_slice, provenance_recs = process_dataset(df_raw, schema, cohort_label=label)
        unified_parts.append(cohort_slice)
        all_provenance.extend(provenance_recs)

    if not unified_parts:
        sys.exit("No valid datasets processed — unified registry not written.")

    # ---- Stack cohorts ----
    print("\nStacking cohorts …")
    unified = pd.concat(unified_parts, ignore_index=True)

    # Drop fully-duplicated columns (shouldn't happen but guard anyway)
    unified = unified.loc[:, ~unified.columns.duplicated()]

    if args.drop_empty_cols:
        clinical = [c for c in unified.columns if c != "cohort"]
        nonempty = [c for c in clinical if unified[c].notna().any()]
        dropped_n = len(clinical) - len(nonempty)
        if dropped_n:
            print(f"  Dropped {dropped_n} all-NaN master column(s) (--drop-empty-cols).")
        unified = unified[["cohort"] + nonempty]

    # ---- Save unified registry ----
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    unified.to_csv(out_path, index=False)

    # ---- Save provenance log ----
    prov_path = Path(args.provenance_output)
    prov_path.parent.mkdir(parents=True, exist_ok=True)
    if all_provenance:
        prov_df = pd.DataFrame(all_provenance)
        prov_df.to_csv(prov_path, index=False)
        print(f"\nProvenance log: {len(prov_df):,} transform records → {prov_path}")
        # Summarize provenance
        n_pass = (prov_df["validation_status"] == "PASS").sum()
        n_fail = (prov_df["validation_status"] == "FAIL").sum()
        print(f"  {n_pass:,} PASS  |  {n_fail:,} FAIL")
    else:
        print(f"\nProvenance log: 0 records (no transforms triggered)")

    # ---- Save harmonization tiers ----
    tiers_path = Path(args.tiers_output)
    tiers_path.parent.mkdir(parents=True, exist_ok=True)
    clinical_cols = [c for c in unified.columns if c != "cohort"]
    tier_records = []
    for col in clinical_cols:
        rule = get_rule(col)
        fill_rate = float(unified[col].notna().mean())
        tier_records.append({
            "master_col": col,
            "tier": rule.tier,
            "data_type": rule.data_type,
            "unit": rule.unit or "",
            "transform": rule.transform or "none",
            "loinc": rule.loinc or "",
            "snomed": rule.snomed or "",
            "phenotype_definition": rule.phenotype_definition or "",
            "timing_window": rule.timing_window or "",
            "allowable_range": (
                f"{rule.allowable_range[0]}-{rule.allowable_range[1]}"
                if rule.allowable_range else ""
            ),
            "fill_rate": f"{fill_rate:.3f}",
        })
    tiers_df = pd.DataFrame(tier_records)
    tiers_df.to_csv(tiers_path, index=False)

    # Tier summary
    tier_counts = tiers_df["tier"].value_counts()
    print(f"\nHarmonization tiers → {tiers_path}")
    for tier_name, cnt in tier_counts.items():
        print(f"  {tier_name}: {cnt} columns")

    # ---- Summary ----
    n_rows = len(unified)
    n_cols = len(unified.columns) - 1
    print(f"\nUnified registry: {n_rows:,} rows × {n_cols} clinical columns")
    print(f"Saved → {out_path}")

    print("\nCoverage by cohort:")
    cohort_counts = unified["cohort"].value_counts()
    for label, cnt in cohort_counts.items():
        fill = unified[unified["cohort"] == label].drop(columns="cohort").notna().mean().mean()
        print(f"  {label}: {cnt:>6} rows  |  column fill rate: {fill:.1%}")

    clinical_cols = [c for c in unified.columns if c != "cohort"]
    fill_rates = unified[clinical_cols].notna().mean().sort_values(ascending=False)
    low_fill = fill_rates[fill_rates < 0.10]
    if not low_fill.empty:
        print(f"\n  {len(low_fill)} column(s) with <10% fill rate:")
        for col, rate in low_fill.head(10).items():
            print(f"    {col}: {rate:.1%}")


if __name__ == "__main__":
    main()
