version: 2

sources:
  - name: raw
    description: "Raw tables loaded by dlt from CSV files"
    schema: public
    tables:
      - name: ehvol_raw
        description: "EHVol cardiovascular dataset — raw CSV ingested by dlt"
        loaded_at_field: _dlt_load_id
